spring:
  application:
    name: product
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: 110110@Lv
      url: jdbc:mysql://localhost:3306/SpringCloud_Sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  rabbitmq:
      addresses: localhost
      password: guest
      port: 5672
      username: guest
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/
  instance:
    prefer-ip-address: true
server:
  port: 8010